export default {
    "login": "rahmadnasutionn",
    "id": 105796328,
    "node_id": "U_kgDOBk5S6A",
    "avatar_url": "https://avatars.githubusercontent.com/u/105796328?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rahmadnasutionn",
    "html_url": "https://github.com/rahmadnasutionn",
    "followers_url": "https://api.github.com/users/rahmadnasutionn/followers",
    "following_url": "https://api.github.com/users/rahmadnasutionn/following{/other_user}",
    "gists_url": "https://api.github.com/users/rahmadnasutionn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rahmadnasutionn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rahmadnasutionn/subscriptions",
    "organizations_url": "https://api.github.com/users/rahmadnasutionn/orgs",
    "repos_url": "https://api.github.com/users/rahmadnasutionn/repos",
    "events_url": "https://api.github.com/users/rahmadnasutionn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rahmadnasutionn/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Rahmad Nasution",
    "company": null,
    "blog": "",
    "location": "Bogor, Jawa Barat",
    "email": "rahmadn241@gmail.com",
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 26,
    "public_gists": 0,
    "followers": 4,
    "following": 0,
    "created_at": "2022-05-18T13:17:08Z",
    "updated_at": "2022-12-31T16:15:03Z"
}