const MockFollower = [{
        "login": "gamemann",
        "id": 6509565,
        "node_id": "MDQ6VXNlcjY1MDk1NjU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6509565?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gamemann",
        "html_url": "https://github.com/gamemann",
        "followers_url": "https://api.github.com/users/gamemann/followers",
        "following_url": "https://api.github.com/users/gamemann/following{/other_user}",
        "gists_url": "https://api.github.com/users/gamemann/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gamemann/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gamemann/subscriptions",
        "organizations_url": "https://api.github.com/users/gamemann/orgs",
        "repos_url": "https://api.github.com/users/gamemann/repos",
        "events_url": "https://api.github.com/users/gamemann/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gamemann/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "scoobytux",
        "id": 72339711,
        "node_id": "MDQ6VXNlcjcyMzM5NzEx",
        "avatar_url": "https://avatars.githubusercontent.com/u/72339711?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/scoobytux",
        "html_url": "https://github.com/scoobytux",
        "followers_url": "https://api.github.com/users/scoobytux/followers",
        "following_url": "https://api.github.com/users/scoobytux/following{/other_user}",
        "gists_url": "https://api.github.com/users/scoobytux/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/scoobytux/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/scoobytux/subscriptions",
        "organizations_url": "https://api.github.com/users/scoobytux/orgs",
        "repos_url": "https://api.github.com/users/scoobytux/repos",
        "events_url": "https://api.github.com/users/scoobytux/events{/privacy}",
        "received_events_url": "https://api.github.com/users/scoobytux/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "vincentkims49",
        "id": 81238908,
        "node_id": "MDQ6VXNlcjgxMjM4OTA4",
        "avatar_url": "https://avatars.githubusercontent.com/u/81238908?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vincentkims49",
        "html_url": "https://github.com/vincentkims49",
        "followers_url": "https://api.github.com/users/vincentkims49/followers",
        "following_url": "https://api.github.com/users/vincentkims49/following{/other_user}",
        "gists_url": "https://api.github.com/users/vincentkims49/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/vincentkims49/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vincentkims49/subscriptions",
        "organizations_url": "https://api.github.com/users/vincentkims49/orgs",
        "repos_url": "https://api.github.com/users/vincentkims49/repos",
        "events_url": "https://api.github.com/users/vincentkims49/events{/privacy}",
        "received_events_url": "https://api.github.com/users/vincentkims49/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "empiretylh",
        "id": 87560915,
        "node_id": "MDQ6VXNlcjg3NTYwOTE1",
        "avatar_url": "https://avatars.githubusercontent.com/u/87560915?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/empiretylh",
        "html_url": "https://github.com/empiretylh",
        "followers_url": "https://api.github.com/users/empiretylh/followers",
        "following_url": "https://api.github.com/users/empiretylh/following{/other_user}",
        "gists_url": "https://api.github.com/users/empiretylh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/empiretylh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/empiretylh/subscriptions",
        "organizations_url": "https://api.github.com/users/empiretylh/orgs",
        "repos_url": "https://api.github.com/users/empiretylh/repos",
        "events_url": "https://api.github.com/users/empiretylh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/empiretylh/received_events",
        "type": "User",
        "site_admin": false
    }
]

export default MockFollower;